language: go
sudo: required
install: true
os:
  - linux
  - osx
go:
  - 1.6.3
  - 1.7.3
  - tip
env:
  matrix:
    - GOARCH=amd64
    - GOARCH=386
before_install:
  - [[ $TRAVIS_OS_NAME == "linux" ]] && sudo sysctl -w net.ipv6.conf.all.disable_ipv6=0
  - [[ $TRAVIS_OS_NAME == "linux" ]] && sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=0
script:
  - ./go.test.bash
  - ./check-fmt.sh
services:
  - redis
  - mongodb
matrix:
  allow_failures:
    - go: tip
notifications:
  slack:
    secure: dDuxAhF7DgwmCvb3V7nu01+RUhvxhOCiBfGVC6596nx93ThjbTgPcMdkAdO7Xk4zFQcH3AiF3+ionMTSk+4oxRIBI0i4p71AkQoFUARWCfmLYWlztZ3Wii4/3bT36bzn5NPqGbNXhx2sWRzOO2W01jQLyFFdZlVKVTBqwBqHqG4=
after_success:
  - bash <(curl -s https://codecov.io/bash)
