language: go
sudo: required
install: true
os:
  - linux
  - osx
go:
  - 1.5.4
  - 1.6.3
  - 1.7rc3
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
  matrix:
    - GOARCH=amd64
    - GOARCH=386
script:
  - go test ./...
  - ./check-fmt.sh
matrix:
  allow_failures:
    - go: tip
notifications:
  slack:
    secure: dDuxAhF7DgwmCvb3V7nu01+RUhvxhOCiBfGVC6596nx93ThjbTgPcMdkAdO7Xk4zFQcH3AiF3+ionMTSk+4oxRIBI0i4p71AkQoFUARWCfmLYWlztZ3Wii4/3bT36bzn5NPqGbNXhx2sWRzOO2W01jQLyFFdZlVKVTBqwBqHqG4=
