language: go
sudo: required
install: true
os:
  - linux
  - osx
go:
  - 1.5.4
  - 1.6.2
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
  matrix:
    - GOARCH=amd64
    - GOARCH=386
before_script:
  - ./misc/install_docker_machine.sh
script:
  - go test -x ./tsuru
  - ./check-fmt.sh
matrix:
  allow_failures:
    - go: tip
