language: go
sudo: false
os:
  - linux
  - osx
go:
  - 1.5.3
  - 1.6
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
  matrix:
    - GOARCH=amd64
    - GOARCH=386
script:
  - go test -x ./tsuru
  - "[ -n \"`gofmt -s -l ./tsuru`\" ] && echo \"gofmt -s -w required for:\" && echo && gofmt -s -l ./tsuru && exit 1 || exit 0"
matrix:
  allow_failures:
    - go: tip
