language: go
sudo: required
install: true
os:
  - linux
  - osx
go:
  - 1.5.4
  - 1.6.2
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
  matrix:
    - GOARCH=amd64
    - GOARCH=386
install:
  - curl -L https://github.com/docker/machine/releases/download/v0.8.0-rc1/docker-machine-`uname -s`-`uname -m` > docker-machine
  - chmod +x ./docker-machine
  - export PATH=$PATH:$PWD

script:
  - go test -x ./tsuru
  - ./check-fmt.sh
matrix:
  allow_failures:
    - go: tip
