version: "3"

services:
  redis:
    image: redis:latest
    networks:
      - tsuru
  
  mongo:
    image: mongo:latest
    networks:
      - tsuru

  planb:
    image: tsuru/planb:latest
    command: --listen :8080 --read-redis-host redis --write-redis-host redis
    ports:
      - 80:8080
    networks:
      - tsuru

  registry:
    image: registry:2
    environment:
      - "REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry"
      - "REGISTRY_HTTP_TLS_CERTIFICATE=/certs/%s:5000/registry-cert.pem" # TEMPLATE
      - "REGISTRY_HTTP_TLS_KEY=/certs/%s:5000/registry-key.pem" # TEMPLATE
    volumes:
      - "/var/lib/registry:/var/lib/registry"
      - "/etc/docker/certs.d:/certs:ro"
    ports:
      - 5000:5000
    networks:
      - tsuru

  tsuru:
    image: tsuru/api:latest # TEMPLATE NA VERSAO
    volumes:
      - "/etc/docker/certs.d:/certs:ro"
    ports:
      - 8080:8080
    networks:
      - tsuru
      
networks:
  tsuru:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.0.9.0/24